spring:
  profiles:
    active: dev
---
# DEV - properties
spring:
  config:
    activate:
      on-profile: dev
weather:
  service:
    endpoint: http://localhost:8000/api/weather
exchange:
  key: eLv5iCMgIh7m0o8X0eM20pdU0XjFFdBI
  url: http://data.fixer.io
  path: /api/latest
server:
  port: 7000
---
#TEST - properties
spring:
  config:
    activate:
      on-profile: test
weather:
  service:
    endpoint: http://localhost:7001/api/weather
exchange:
  key: secretKey
  url: http://localhost:7001/
  path: /api/latest
server:
  port: 7001
